### ISSUE TITLE
exchanging  jpeg or png files over it

### ISSUE THREAD

**Issue by meshubhama01** [lalrishav/HubPort#2]
you should add this as well

**Comment by lalrishav** [comment]
well you can upload any type of file,the user will get it

**Comment by lalrishav** [comment]
If you want any change you can contribute

**Comment by meshubhama01** [comment]
in your code if jpeg file is send it will be taken as text only so i guess we will need binary passing..
i will try

**Comment by lalrishav** [comment]
even video,exe and any extension can be sent over the network

**Comment by lalrishav** [comment]
you can try it out
