### ISSUE TITLE
encoding shared file

### ISSUE THREAD

**Issue by meshubhama01** [lalrishav/HubPort#4]
the way you are encoding and decoding files in client.py (line 39-41) it encodes  the jpeg type in a wrong way or in a text way even after what i suggest on server.py
i know how to encode jpeg file i will create a new file for that. but how to use it on client.py thats quite tricky and you need to see this

**Comment by lalrishav** [comment]
Line 39-41 is not encoding or decoding any file type.It just recieves and decode the name of the file i.e encoded in an list and then sent over the socket,notice just name of the file which is just a string and not the whole file.

**Comment by lalrishav** [comment]
Please try to contribute for automatic wifi connection issue
